/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_inventory_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_inventory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_inventory__product_id__get"];
        /** Update Product */
        put: operations["update_product_api_inventory__product_id__put"];
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_inventory__product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Parties */
        get: operations["list_parties_api_parties_get"];
        put?: never;
        /** Create Party */
        post: operations["create_party_api_parties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parties/{party_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Party */
        get: operations["get_party_api_parties__party_id__get"];
        /** Update Party */
        put: operations["update_party_api_parties__party_id__put"];
        post?: never;
        /** Delete Party */
        delete: operations["delete_party_api_parties__party_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parties/{party_id}/adjust-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust Balance */
        post: operations["adjust_balance_api_parties__party_id__adjust_balance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sales */
        get: operations["list_sales_api_sales_get"];
        put?: never;
        /** Create Sale */
        post: operations["create_sale_api_sales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/{sale_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sale */
        get: operations["get_sale_api_sales__sale_id__get"];
        /** Update Sale */
        put: operations["update_sale_api_sales__sale_id__put"];
        post?: never;
        /** Delete Sale */
        delete: operations["delete_sale_api_sales__sale_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/{sale_id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Payment */
        post: operations["record_payment_api_sales__sale_id__payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Purchases */
        get: operations["list_purchases_api_purchases_get"];
        put?: never;
        /** Create Purchase */
        post: operations["create_purchase_api_purchases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchases/{purchase_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Purchase */
        get: operations["get_purchase_api_purchases__purchase_id__get"];
        /** Update Purchase */
        put: operations["update_purchase_api_purchases__purchase_id__put"];
        post?: never;
        /** Delete Purchase */
        delete: operations["delete_purchase_api_purchases__purchase_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchases/{purchase_id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Payment */
        post: operations["record_payment_api_purchases__purchase_id__payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Expenses */
        get: operations["list_expenses_api_expenses_get"];
        put?: never;
        /** Create Expense */
        post: operations["create_expense_api_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Expense */
        get: operations["get_expense_api_expenses__expense_id__get"];
        /** Update Expense */
        put: operations["update_expense_api_expenses__expense_id__put"];
        post?: never;
        /** Delete Expense */
        delete: operations["delete_expense_api_expenses__expense_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quotations */
        get: operations["list_quotations_api_quotations_get"];
        put?: never;
        /** Create Quotation */
        post: operations["create_quotation_api_quotations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotations/{quotation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quotation */
        get: operations["get_quotation_api_quotations__quotation_id__get"];
        /** Update Quotation */
        put: operations["update_quotation_api_quotations__quotation_id__put"];
        post?: never;
        /** Delete Quotation */
        delete: operations["delete_quotation_api_quotations__quotation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/trading-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trading Account */
        get: operations["trading_account_api_reports_trading_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/profit-and-loss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profit And Loss */
        get: operations["profit_and_loss_api_reports_profit_and_loss_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balance Sheet */
        get: operations["balance_sheet_api_reports_balance_sheet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/outstanding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outstanding Report */
        get: operations["outstanding_report_api_reports_outstanding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transaction History */
        get: operations["transaction_history_api_reports_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_company_get"];
        /** Upsert Profile */
        put: operations["upsert_profile_api_company_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_ledger_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/accounts/{account_name}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Balance */
        get: operations["account_balance_api_ledger_accounts__account_name__balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/gst-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gst Summary */
        get: operations["gst_summary_api_ledger_gst_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/account-balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Balances */
        get: operations["account_balances_api_ledger_account_balances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BalanceAdjust */
        BalanceAdjust: {
            /** Amount */
            amount: number | string;
        };
        /** CompanyResponse */
        CompanyResponse: {
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Name */
            name: string;
            /** Business Type */
            business_type?: string | null;
            /** Category */
            category?: string | null;
            /** Beginning Date */
            beginning_date?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Address */
            address?: string | null;
            /** Logo Path */
            logo_path?: string | null;
            /** Qr Path */
            qr_path?: string | null;
        };
        /** CompanyUpdate */
        CompanyUpdate: {
            /** Name */
            name: string;
            /** Business Type */
            business_type?: string | null;
            /** Category */
            category?: string | null;
            /** Beginning Date */
            beginning_date?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Address */
            address?: string | null;
            /** Logo Path */
            logo_path?: string | null;
            /** Qr Path */
            qr_path?: string | null;
        };
        /** ExpenseCreate */
        ExpenseCreate: {
            /** Category */
            category: string;
            /**
             * Paid By
             * @default Cash
             */
            paid_by: string;
            /** Amount */
            amount: number | string;
            /** Notes */
            notes?: string | null;
        };
        /** ExpenseResponse */
        ExpenseResponse: {
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Category */
            category: string;
            /** Paid By */
            paid_by: string;
            /** Amount */
            amount: string;
            /** Notes */
            notes?: string | null;
        };
        /** ExpenseUpdate */
        ExpenseUpdate: {
            /** Category */
            category?: string | null;
            /** Paid By */
            paid_by?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PartyCreate */
        PartyCreate: {
            /** Name */
            name: string;
            party_type: components["schemas"]["PartyType"];
            /**
             * Balance
             * @default 0
             */
            balance: number | string;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * State
             * @default
             */
            state: string;
            /** Gstin */
            gstin?: string | null;
        };
        /** PartyResponse */
        PartyResponse: {
            /**
             * Party Id
             * Format: uuid
             */
            party_id: string;
            /** Name */
            name: string;
            party_type: components["schemas"]["PartyType"];
            /** Balance */
            balance: string;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * State
             * @default
             */
            state: string;
            /** Gstin */
            gstin?: string | null;
        };
        /**
         * PartyType
         * @enum {string}
         */
        PartyType: "DEBTOR" | "CREDITOR";
        /** PartyUpdate */
        PartyUpdate: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** PaymentCreate */
        PaymentCreate: {
            /** Amount */
            amount: number | string;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Selling Price */
            selling_price: number | string;
            /** Quantity */
            quantity: number;
            /**
             * Gst Rate
             * @default 0
             */
            gst_rate: number | string;
            /**
             * Hsn Code
             * @default
             */
            hsn_code: string;
        };
        /** ProductResponse */
        ProductResponse: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name: string;
            /** Selling Price */
            selling_price: string;
            /** Quantity */
            quantity: number;
            /** Gst Rate */
            gst_rate: string;
            /** Hsn Code */
            hsn_code: string;
            /** Archived */
            archived: boolean;
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Selling Price */
            selling_price?: number | string | null;
            /** Quantity */
            quantity?: number | null;
            /** Gst Rate */
            gst_rate?: number | string | null;
            /** Hsn Code */
            hsn_code?: string | null;
        };
        /** PurchaseCreate */
        PurchaseCreate: {
            /** Items Data */
            items_data: components["schemas"]["PurchaseItemInput"][];
            /** Party Id */
            party_id?: string | null;
            /**
             * Paid Amount
             * @default 0
             */
            paid_amount: number | string;
            /**
             * Round Off
             * @default false
             */
            round_off: boolean;
            /**
             * Tax Inclusive
             * @default false
             */
            tax_inclusive: boolean;
        };
        /** PurchaseItemInput */
        PurchaseItemInput: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: number | string;
            /** Discount Perc */
            discount_perc?: number | string | null;
            /** Discount Amt */
            discount_amt?: number | string | null;
            /** Tax Perc */
            tax_perc?: number | string | null;
        };
        /** PurchaseItemResponse */
        PurchaseItemResponse: {
            /**
             * Purchase Item Id
             * Format: uuid
             */
            purchase_item_id: string;
            /**
             * Purchase Id
             * Format: uuid
             */
            purchase_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: string;
            /** Discount Amount */
            discount_amount: string;
            /** Taxable Amount */
            taxable_amount: string;
            /** Tax Amount */
            tax_amount: string;
            /** Cgst Amount */
            cgst_amount: string;
            /** Sgst Amount */
            sgst_amount: string;
            /** Igst Amount */
            igst_amount: string;
            /** Row Total */
            row_total: string;
        };
        /** PurchaseResponse */
        PurchaseResponse: {
            /**
             * Purchase Id
             * Format: uuid
             */
            purchase_id: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Party Id */
            party_id?: string | null;
            /** Total Taxable */
            total_taxable: string;
            /** Total Tax */
            total_tax: string;
            /** Grand Total */
            grand_total: string;
            /** Paid Amount */
            paid_amount: string;
            /** Balance Amount */
            balance_amount: string;
            /** Due Date */
            due_date?: string | null;
            /** Round Off */
            round_off: boolean;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["PurchaseItemResponse"][];
        };
        /** QuotationCreate */
        QuotationCreate: {
            /** Party Id */
            party_id?: string | null;
            /**
             * Status
             * @default Draft
             */
            status: string;
            /** Notes */
            notes?: string | null;
            /** Items */
            items: components["schemas"]["QuotationItemInput"][];
        };
        /** QuotationItemInput */
        QuotationItemInput: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number | string;
        };
        /** QuotationItemResponse */
        QuotationItemResponse: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Quotation Id
             * Format: uuid
             */
            quotation_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Total Price */
            total_price: string;
        };
        /** QuotationResponse */
        QuotationResponse: {
            /**
             * Quotation Id
             * Format: uuid
             */
            quotation_id: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Party Id */
            party_id?: string | null;
            /** Total Amount */
            total_amount: string;
            /**
             * Status
             * @default Draft
             */
            status: string;
            /** Notes */
            notes?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["QuotationItemResponse"][];
        };
        /** SaleCreate */
        SaleCreate: {
            /** Items Data */
            items_data: components["schemas"]["SaleItemInput"][];
            /** Party Id */
            party_id?: string | null;
            /**
             * Paid Amount
             * @default 0
             */
            paid_amount: number | string;
            /**
             * Round Off
             * @default false
             */
            round_off: boolean;
            /**
             * Tax Inclusive
             * @default false
             */
            tax_inclusive: boolean;
        };
        /** SaleItemInput */
        SaleItemInput: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Quantity */
            quantity: number;
            /** Discount Perc */
            discount_perc?: number | string | null;
            /** Discount Amt */
            discount_amt?: number | string | null;
            /** Tax Perc */
            tax_perc?: number | string | null;
        };
        /** SaleItemResponse */
        SaleItemResponse: {
            /**
             * Sale Item Id
             * Format: uuid
             */
            sale_item_id: string;
            /**
             * Sale Id
             * Format: uuid
             */
            sale_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: string;
            /** Discount Amount */
            discount_amount: string;
            /** Taxable Amount */
            taxable_amount: string;
            /** Tax Amount */
            tax_amount: string;
            /** Cgst Amount */
            cgst_amount: string;
            /** Sgst Amount */
            sgst_amount: string;
            /** Igst Amount */
            igst_amount: string;
            /** Row Total */
            row_total: string;
        };
        /** SaleResponse */
        SaleResponse: {
            /**
             * Sale Id
             * Format: uuid
             */
            sale_id: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Party Id */
            party_id?: string | null;
            /** Total Taxable */
            total_taxable: string;
            /** Total Tax */
            total_tax: string;
            /** Grand Total */
            grand_total: string;
            /** Paid Amount */
            paid_amount: string;
            /** Balance Amount */
            balance_amount: string;
            /** Due Date */
            due_date?: string | null;
            /** Round Off */
            round_off: boolean;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["SaleItemResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_products_api_inventory_get: {
        parameters: {
            query?: {
                show_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_inventory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_inventory__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_inventory__product_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_inventory__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_parties_api_parties_get: {
        parameters: {
            query?: {
                party_type?: components["schemas"]["PartyType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_party_api_parties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_party_api_parties__party_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_party_api_parties__party_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_party_api_parties__party_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_balance_api_parties__party_id__adjust_balance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BalanceAdjust"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sales_api_sales_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleResponse"][];
                };
            };
        };
    };
    create_sale_api_sales_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sale_api_sales__sale_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sale_api_sales__sale_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sale_api_sales__sale_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_payment_api_sales__sale_id__payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_purchases_api_purchases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseResponse"][];
                };
            };
        };
    };
    create_purchase_api_purchases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_purchase_api_purchases__purchase_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_purchase_api_purchases__purchase_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_purchase_api_purchases__purchase_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_payment_api_purchases__purchase_id__payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_api_expenses_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_api_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expense_api_expenses__expense_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_expense_api_expenses__expense_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_expense_api_expenses__expense_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quotations_api_quotations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotationResponse"][];
                };
            };
        };
    };
    create_quotation_api_quotations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuotationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quotation_api_quotations__quotation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quotation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quotation_api_quotations__quotation_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quotation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuotationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_quotation_api_quotations__quotation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quotation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trading_account_api_reports_trading_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    profit_and_loss_api_reports_profit_and_loss_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    balance_sheet_api_reports_balance_sheet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    outstanding_report_api_reports_outstanding_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    transaction_history_api_reports_transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_profile_api_company_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
        };
    };
    upsert_profile_api_company_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_ledger_transactions_get: {
        parameters: {
            query?: {
                account_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_balance_api_ledger_accounts__account_name__balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gst_summary_api_ledger_gst_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    account_balances_api_ledger_account_balances_get: {
        parameters: {
            query: {
                /** @description Comma-separated account names */
                accounts: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
